# Experiment Configuration
simulation_names: 
  - 'DG'

filter_scales:
  - '50'
  - '100'
  - '200'
  - '400'

window_size: 1

input_channels: 
  - 'dudx_widened'
  - 'dvdx_widened'
  - 'dudy_widened'
  - 'dvdy_widened'
  - 'dhdx_widened'
  - 'dhdy_widened'
  - 'filter_scale'

output_channels: 
  - 'uphp'
  - 'vphp'

coeff_channels: []

train_time_range: [0, 640]
test_time_range: [-64, null]

num_train_batches: 37
num_test_batches: 5

network_shape: [36, 36, 2]